# Site settings
title: James Tunnell - thoughts, insights, and whatnot
email: jamestunnell@gmail.com
description: "A place to post thoughts on and insights from my work."
baseurl: ""
url: "http://jamestunnell.github.io"
usernames:
    twitter: aptlydone
    github: jamestunnell

# Build settings
markdown: kramdown
permalink: pretty
timezone: "America/Vancouver"
